apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.kushihiko.tech`)
      kind: Rule
      services:
        - name: grafana
          port: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingressroute-secure
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.kushihiko.tech`)
      kind: Rule
      services:
        - name: grafana
          port: 80
  tls:
    certResolver: cloudflare