apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: grafana
    releaseName: grafana
    includeCRDs: true
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml
resources:
  - ingressroute.yaml