apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: flux2
    releaseName: flux
    includeCRDs: true
    repo: https://fluxcd-community.github.io/helm-charts
    valuesFile: values.yaml