apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - ingressroute.yaml
helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: kustomizer
      app.kubernetes.io/name: grafana