apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv.yaml
helmCharts:
  - name: loki
    releaseName: loki
    includeCRDs: true
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml