kind: PersistentVolume
apiVersion: v1
metadata:
  name: loki-pv
  labels:
    type: local
    app.kubernetes.io/name: loki
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/loki-pv"