apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: fluent-bit
    releaseName: fluent-bit
    includeCRDs: true
    repo: https://fluent.github.io/helm-charts
    valuesFile: values.yaml