apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: opensearch
    releaseName: opensearch
    includeCRDs: true
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values.yaml
resources:
  - ingressroute.yaml