---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
data:
  loki.yaml: |
    auth_enabled: false
    ingester:
      max_chunk_age: 8h
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      reject_old_samples: false
      allow_structured_metadata: false
    schema_config:
      configs:
        - from: "2020-02-01"
          index:
            period: 168h
            prefix: index_
          object_store: filesystem
          schema: v11
          store: boltdb
    server:
      http_listen_port: 3100
    common:
      path_prefix: /data
      storage:
        filesystem:
          chunks_directory: /data/chunks
          rules_directory: /data/rules
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
