apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cm.yaml
  - service.yaml
  - service-headless.yaml
  - statefulset.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: kustomizer
      app.kubernetes.io/name: loki
