apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - account.yaml
  - clusterrole.yaml
  - crb.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml