---
- name: Ensure deploy directory exists
  file:
    path: "{{ service_directory }}"
    state: directory

- name: Copy docker-compose.yml from template
  template:
    src: docker-compose.yml
    dest: "{{ service_directory }}/docker-compose.yml"
    mode: '0644'

- name: Deploy using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ service_directory }}"
    state: present