apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: chronograf
    releaseName: chronograf
    includeCRDs: true
    repo: https://helm.influxdata.com/
    valuesFile: values.yaml
resources:
  - ingressroute.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: kustomizer
      app.kubernetes.io/name: chronograf
