---
- name: Ensure deploy directory exists
  file:
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: "{{ service_directory }}"}
    - { path: "{{ service_directory }}/certs"}

- name: Copy Templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "docker-compose.yml", dest: "{{ service_directory }}/docker-compose.yml", mode: "0644" }
    - { src: "traefik.yml", dest: "{{ service_directory}}/traefik.yml", mode: "0644" }
    - { src: "traefik.env", dest: "{{ service_directory}}/traefik.env", mode: "0644" }

- name: Copy docker-compose.yml from template
  template:
    src: docker-compose.yml
    dest: "{{ service_directory }}/docker-compose.yml"
    mode: '0644'

- name: Deploy using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ service_directory }}"
    state: present