apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
  REPLICATION_PASSWORD: cmVwbGljYXRpb25QYXNzd29yZA==
  REPLICATION_USER: cmVwbGljYXRpb251c2Vy
type: Opaque
