apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volume.yaml
  - secrets.yaml
  - ingressroute.yaml
helmCharts:
  - name: influxdb2
    releaseName: influxdb2
    includeCRDs: true
    repo: https://helm.influxdata.com/
    valuesFile: values.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: kustomizer
      app.kubernetes.io/name: influxdb
