---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - account.yaml
  - daemonset.yaml
  - cm.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: kustomizer
      app.kubernetes.io/name: promtail
