apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    app.kubernetes.io/created-by: kustomizer
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/name: influxdb
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb"