apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
helmCharts:
  - name: traefik
    releaseName: traefik
    includeCRDs: true
    repo: https://traefik.github.io/charts
    valuesFile: values.yaml