apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: promtail
    releaseName: promtail
    includeCRDs: true
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml